/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laptrinhjava;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static laptrinhjava.Program.con;

/**
 *
 * @author DUY ANH B2012173
 */
public class BangDiemHocKy extends javax.swing.JFrame {
    private static BangDiemHocKy instance;
    private Object Mssv = "";
    public BangDiemHocKy() {
        initComponents();
    }
    
    public static synchronized BangDiemHocKy getInstance(Object mssv){
        if(instance==null){
            instance = new BangDiemHocKy();
            instance.setVisible(true);
            instance.Mssv = mssv;
            if(instance.checkDiem()){
                instance.reloadNamHoc();
                instance.setName();
            }
        } else{
            instance.NamHoc.getModel().setSelectedItem("-Năm học-");
            instance.setVisible(true);
            instance.Mssv = mssv;
            if(instance.checkDiem()){
                instance.reloadNamHoc();
                instance.setName();
            }
        }
        return instance;
    }

    public void setName(){
        try {
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("select HoTen, NamSinh, TenLop from SinhVien inner join Lop on SinhVien.MaLop = Lop.MaLop where MSSV = N'"+Mssv+"';");
            
            rs.next();
            Object[] obj = {rs.getString(1), rs.getInt(2), rs.getString(3)};
            MSSV.setText((String) Mssv);
            Hoten.setText(String.valueOf(obj[0]));
            NamSinh.setText(String.valueOf(obj[1]));
            TenLop.setText(String.valueOf(obj[2]));
        } catch (SQLException ex) {
            Logger.getLogger(BangDiemHocKy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public boolean checkDiem(){
        try {
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("SELECT NamHoc from Diem WHERE MSSV = N'"+Mssv+"' GROUP BY NamHoc;");
            DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
            m.setRowCount(0);
            DiemTB.setText("Điểm TB");
            if(rs.next()){
                s.close();
                return true;
            }
            else{
                JOptionPane.showMessageDialog(this, "Sinh viên này chưa có điểm", "Bảng điểm trống", JOptionPane.INFORMATION_MESSAGE);
                DefaultComboBoxModel<String> CBmodel = (DefaultComboBoxModel<String>) NamHoc.getModel();
                CBmodel.removeAllElements();
                CBmodel = (DefaultComboBoxModel<String>) HocKy.getModel();
                CBmodel.removeAllElements();
                DiemTB.setText("Điểm TB");
                NamHoc.setSelectedItem("-Năm học-");
                HocKy.setSelectedItem("-Học kỳ-");
                return false;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ReloadBtn = new javax.swing.JButton();
        CloseBtn = new javax.swing.JButton();
        XepLoai = new javax.swing.JTextField();
        DiemTB = new javax.swing.JTextField();
        NamSinh = new javax.swing.JTextField();
        TenLop = new javax.swing.JTextField();
        MSSV = new javax.swing.JTextField();
        Hoten = new javax.swing.JTextField();
        HocKy = new javax.swing.JComboBox<>();
        NamHoc = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(550, 170));
        setSize(new java.awt.Dimension(0, 0));

        JPanel1.setBackground(new java.awt.Color(255, 255, 255));
        JPanel1.setFont(new java.awt.Font("Futura Bk", 0, 18)); // NOI18N
        JPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 204));
        jLabel1.setFont(new java.awt.Font("Futura Bk", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ ĐIỂM SINH VIÊN");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jLabel1.setOpaque(true);
        JPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 340, 40));

        ReloadBtn.setBackground(new java.awt.Color(204, 204, 204));
        ReloadBtn.setFont(new java.awt.Font("Futura Hv", 0, 18)); // NOI18N
        ReloadBtn.setText("Load");
        ReloadBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ReloadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReloadBtnActionPerformed(evt);
            }
        });
        JPanel1.add(ReloadBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 100, 40));

        CloseBtn.setBackground(new java.awt.Color(204, 204, 204));
        CloseBtn.setFont(new java.awt.Font("Futura Hv", 0, 18)); // NOI18N
        CloseBtn.setText("Close");
        CloseBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });
        JPanel1.add(CloseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 100, 40));

        XepLoai.setFont(new java.awt.Font("Futura Bk", 0, 18));
        XepLoai.setText("Xếp loại");
        XepLoai.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        XepLoai.setEnabled(false);
        XepLoai.setMargin(new java.awt.Insets(1, 5, 1, 5));
        XepLoai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XepLoaiMouseClicked(evt);
            }
        });
        JPanel1.add(XepLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 160, 30));

        DiemTB.setFont(new java.awt.Font("Futura Bk", 0, 19));
        DiemTB.setText("Điểm TB");
        DiemTB.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        DiemTB.setEnabled(false);
        DiemTB.setMargin(new java.awt.Insets(1, 5, 1, 5));
        DiemTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DiemTBMouseClicked(evt);
            }
        });
        JPanel1.add(DiemTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 160, 30));

        NamSinh.setFont(new java.awt.Font("Futura Bk", 0, 16));
        NamSinh.setText("Năm sinh");
        NamSinh.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        NamSinh.setEnabled(false);
        NamSinh.setMargin(new java.awt.Insets(2, 7, 3, 7));
        JPanel1.add(NamSinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 290, 30));

        TenLop.setFont(new java.awt.Font("Futura Bk", 0, 16));
        TenLop.setText("Tên lớp");
        TenLop.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TenLop.setEnabled(false);
        TenLop.setMargin(new java.awt.Insets(2, 7, 3, 7));
        JPanel1.add(TenLop, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 290, 30));

        MSSV.setFont(new java.awt.Font("Futura Bk", 0, 16));
        MSSV.setText("MSSV");
        MSSV.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        MSSV.setEnabled(false);
        MSSV.setMargin(new java.awt.Insets(2, 7, 3, 7));
        JPanel1.add(MSSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 230, 30));

        Hoten.setFont(new java.awt.Font("Futura Bk", 0, 16));
        Hoten.setText("Họ tên");
        Hoten.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Hoten.setEnabled(false);
        Hoten.setMargin(new java.awt.Insets(2, 7, 3, 7));
        JPanel1.add(Hoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 230, 30));

        HocKy.setToolTipText("Học kỳ");
        HocKy.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                HocKyItemStateChanged(evt);
            }
        });
        HocKy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HocKyMouseClicked(evt);
            }
        });
        JPanel1.add(HocKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 120, 140, 30));

        NamHoc.setToolTipText("Năm Học");
        NamHoc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NamHocItemStateChanged(evt);
            }
        });
        JPanel1.add(NamHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 80, 140, 30));

        jLabel9.setFont(new java.awt.Font("Futura Bk", 0, 18)); // NOI18N
        jLabel9.setText("Xếp loại học kỳ");
        JPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 150, 30));

        jLabel8.setFont(new java.awt.Font("Futura Bk", 0, 18)); // NOI18N
        jLabel8.setText("Học kỳ");
        JPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, 60, 30));

        jLabel7.setFont(new java.awt.Font("Futura Bk", 0, 18)); // NOI18N
        jLabel7.setText("Năm học");
        JPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 80, 30));

        jLabel2.setFont(new java.awt.Font("Futura Bk", 0, 18)); // NOI18N
        jLabel2.setText("Họ tên");
        JPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 60, 30));

        jLabel3.setFont(new java.awt.Font("Futura Bk", 0, 18)); // NOI18N
        jLabel3.setText("Tên lớp");
        JPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 60, 30));

        jLabel4.setFont(new java.awt.Font("Futura Bk", 0, 18)); // NOI18N
        jLabel4.setText("MSSV");
        JPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 60, 30));

        jLabel5.setFont(new java.awt.Font("Futura Bk", 0, 18)); // NOI18N
        jLabel5.setText("Năm sinh");
        JPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 90, 30));

        jLabel12.setFont(new java.awt.Font("Futura Bk", 0, 18)); // NOI18N
        jLabel12.setText("Trung bình học kỳ");
        JPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 150, 30));

        jTable1.setBackground(new java.awt.Color(255, 255, 204));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Môn học", "Điểm lần 1", "Điểm lần 2", "Điểm TB", "Xếp loại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(27);
        jTable1.setRowSelectionAllowed(false);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(250);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(65);
        jScrollPane2.setViewportView(jTable1);

        JPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 940, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1028, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void reloadNamHoc(){
        try {
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("SELECT NamHoc from Diem WHERE MSSV = N'"+Mssv+"' GROUP BY NamHoc;");
            DefaultComboBoxModel<String> CBmodel = (DefaultComboBoxModel<String>) NamHoc.getModel();
            CBmodel.removeAllElements();
            while(rs.next()){
                CBmodel.addElement(rs.getString(1));
            }
            CBmodel.setSelectedItem("-Năm học-");
            CBmodel = (DefaultComboBoxModel<String>) HocKy.getModel();
            CBmodel.removeAllElements();
            DiemTB.setText("Điểm TB");
            XepLoai.setText("Xếp loại");
            s.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    private void ReloadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReloadBtnActionPerformed
        if(con == null){
            JOptionPane.showMessageDialog(this, "Vui lòng kết nối trước!", "Chưa kết nối", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(HocKy.getSelectedIndex()==-1){
            return;
        }
        try {
            int hocky = Integer.parseInt((String) HocKy.getSelectedItem());
            String namhoc = String.valueOf(NamHoc.getSelectedItem());
            Statement s = con.createStatement();
            DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
            m.setRowCount(0);
            ResultSet rs = s.executeQuery("select TenMH, DiemLan1, DiemLan2, DiemTB, XepLoai from Diem "
                    + " inner join MonHoc on MonHoc.MaMH = Diem.MaMH where MSSV = N'"+Mssv+"'"
                            + "AND NamHoc = N'"+namhoc+"' AND HocKy = "+hocky+";");
            double tb = 0.0;
            int sl = 0;
            while(rs.next()){
                Object[] obj = {rs.getString(1), rs.getFloat(2), rs.getFloat(3), rs.getFloat(4), rs.getString(5)};
                m.addRow(obj);
                sl++;
                tb += rs.getDouble(4);
            }
            tb = tb/sl;
            DecimalFormat decimalFormat = new DecimalFormat("#.##");
            String formattedTB = decimalFormat.format(tb);
            DiemTB.setText(String.valueOf(formattedTB));
            double diemTB = tb;
            String ketQua;
            if (diemTB < 4.0) {
                ketQua = "Rớt";
            } else if (diemTB >= 4.0 && diemTB <= 5.4) {
                ketQua = "Yếu";
            } else if (diemTB >= 5.5 && diemTB <= 6.9) {
                ketQua = "Trung Bình";
            } else if (diemTB >= 7.0 && diemTB <= 8.4) {
                ketQua = "Khá";
            } else if (diemTB >= 8.5 && diemTB <= 10.0) {
                ketQua = "Giỏi";
            } else {
                ketQua = "Không hợp lệ";
            }
            XepLoai.setText(ketQua);
            s.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_ReloadBtnActionPerformed

    
    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        try {
            this.setVisible(false);
            QLTTSV.getInstance().reloadTTSV();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_CloseBtnActionPerformed

    private void XepLoaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XepLoaiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_XepLoaiMouseClicked

    private void DiemTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiemTBMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DiemTBMouseClicked

    private void NamHocItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NamHocItemStateChanged
        if(NamHoc.getSelectedIndex()==-1){
            DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
            m.setRowCount(0);
            return;
        }
        try {
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("SELECT HocKy from Diem WHERE MSSV = N'"+Mssv+"' AND NamHoc=N'"+NamHoc.getSelectedItem().toString()+"' GROUP BY HocKy;");
            DefaultComboBoxModel<String> CBmodel = (DefaultComboBoxModel<String>) HocKy.getModel();
            CBmodel.removeAllElements();
            while(rs.next()){
                CBmodel.addElement(String.valueOf(rs.getInt(1)));
            }
//            CBmodel.setSelectedItem("-Học kỳ-");
            s.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_NamHocItemStateChanged

    private void HocKyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_HocKyItemStateChanged
        if(HocKy.getSelectedIndex()==-1 || HocKy.getSelectedItem().equals("-Học kỳ-")){
            return;
        }
        if(HocKy.getSelectedItem().equals("1") || HocKy.getSelectedItem().equals("2") || HocKy.getSelectedItem().equals("3"))
        this.ReloadBtn.doClick();
    }//GEN-LAST:event_HocKyItemStateChanged

    private void HocKyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HocKyMouseClicked
        if(HocKy.getItemCount()==0){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn năm học trước!", "Chưa chọn năm học", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_HocKyMouseClicked
    
    public void reloadTTSV(){
        this.ReloadBtn.doClick();
    }
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseBtn;
    private javax.swing.JTextField DiemTB;
    private javax.swing.JComboBox<String> HocKy;
    private javax.swing.JTextField Hoten;
    private javax.swing.JPanel JPanel1;
    private javax.swing.JTextField MSSV;
    private javax.swing.JComboBox<String> NamHoc;
    private javax.swing.JTextField NamSinh;
    private javax.swing.JButton ReloadBtn;
    private javax.swing.JTextField TenLop;
    private javax.swing.JTextField XepLoai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
