/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laptrinhjava;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import static laptrinhjava.Program.con;

/**
 *
 * @author DUY ANH B2012173
 */
public class NhapDiem extends javax.swing.JFrame {
    private static NhapDiem instance; 
    private String stt = "";
    private static int exist = -1;
    private Object Mssv = "";
    public NhapDiem() {
        initComponents();
    }
    
    public static synchronized NhapDiem getInstance(Object mssv){
        if(instance==null){
            instance = new NhapDiem();
            instance.MonHocCB.getModel().setSelectedItem("-Môn học-");
            instance.reloadMonHoc();
            instance.setVisible(true);
            instance.Mssv = mssv;
            instance.ReloadBtn.doClick();
            instance.reset();
        } else{
            instance.MonHocCB.getModel().setSelectedItem("-Môn học-");
            instance.setVisible(true);
            instance.Mssv = mssv;
            instance.ReloadBtn.doClick();
            instance.reset();
        }
        return instance;
    }

    public void reset(){
        exist = -1;
        NamHoc.setSelectedIndex(6);
        HocKy.setSelectedIndex(0);
        DiemL1.setText("Điểm lần 1");
        DiemL2.setText("Điểm lần 2");
        DiemTB.setText("Điểm TB");
        XepLoai.setText("Xếp loại");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ReloadBtn = new javax.swing.JButton();
        SaveBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        CloseBtn = new javax.swing.JButton();
        XepLoai = new javax.swing.JTextField();
        DiemTB = new javax.swing.JTextField();
        DiemL2 = new javax.swing.JTextField();
        DiemL1 = new javax.swing.JTextField();
        NamSinh = new javax.swing.JTextField();
        TenLop = new javax.swing.JTextField();
        MSSV = new javax.swing.JTextField();
        Hoten = new javax.swing.JTextField();
        HocKy = new javax.swing.JComboBox<>();
        NamHoc = new javax.swing.JComboBox<>();
        MonHocCB = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(550, 170));
        setSize(new java.awt.Dimension(0, 0));

        JPanel1.setBackground(new java.awt.Color(255, 255, 255));
        JPanel1.setFont(new java.awt.Font("Futura Bk", 0, 18)); // NOI18N
        JPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 204));
        jLabel1.setFont(new java.awt.Font("Futura Bk", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ ĐIỂM SINH VIÊN");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jLabel1.setOpaque(true);
        JPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 340, 40));

        ReloadBtn.setBackground(new java.awt.Color(204, 204, 204));
        ReloadBtn.setFont(new java.awt.Font("Futura Hv", 0, 18)); // NOI18N
        ReloadBtn.setText("Load");
        ReloadBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ReloadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReloadBtnActionPerformed(evt);
            }
        });
        JPanel1.add(ReloadBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 100, 40));

        SaveBtn.setBackground(new java.awt.Color(204, 204, 204));
        SaveBtn.setFont(new java.awt.Font("Futura Hv", 0, 18)); // NOI18N
        SaveBtn.setText("Save");
        SaveBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        JPanel1.add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 100, 40));

        DeleteBtn.setBackground(new java.awt.Color(204, 204, 204));
        DeleteBtn.setFont(new java.awt.Font("Futura Hv", 0, 18)); // NOI18N
        DeleteBtn.setText("Delete");
        DeleteBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });
        JPanel1.add(DeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, 100, 40));

        CloseBtn.setBackground(new java.awt.Color(204, 204, 204));
        CloseBtn.setFont(new java.awt.Font("Futura Hv", 0, 18)); // NOI18N
        CloseBtn.setText("Close");
        CloseBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });
        JPanel1.add(CloseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 100, 40));

        XepLoai.setFont(new java.awt.Font("Futura Bk", 0, 18));
        XepLoai.setText("Xếp loại");
        XepLoai.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        XepLoai.setEnabled(false);
        XepLoai.setMargin(new java.awt.Insets(1, 5, 1, 5));
        XepLoai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XepLoaiMouseClicked(evt);
            }
        });
        JPanel1.add(XepLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 160, 30));

        DiemTB.setFont(new java.awt.Font("Futura Bk", 0, 19));
        DiemTB.setText("Điểm TB");
        DiemTB.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        DiemTB.setEnabled(false);
        DiemTB.setMargin(new java.awt.Insets(1, 5, 1, 5));
        DiemTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DiemTBMouseClicked(evt);
            }
        });
        JPanel1.add(DiemTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 160, 30));

        DiemL2.setFont(new java.awt.Font("Futura Bk", 0, 19));
        DiemL2.setText("Điểm lần 2");
        DiemL2.setMargin(new java.awt.Insets(2, 7, 3, 7));
        DiemL2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DiemL2MouseClicked(evt);
            }
        });
        JPanel1.add(DiemL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 110, 30));

        DiemL1.setFont(new java.awt.Font("Futura Bk", 0, 19));
        DiemL1.setText("Điểm lần 1");
        DiemL1.setMargin(new java.awt.Insets(2, 7, 3, 7));
        DiemL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DiemL1MouseClicked(evt);
            }
        });
        JPanel1.add(DiemL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 110, 30));

        NamSinh.setFont(new java.awt.Font("Futura Bk", 0, 16));
        NamSinh.setText("Năm sinh");
        NamSinh.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        NamSinh.setEnabled(false);
        NamSinh.setMargin(new java.awt.Insets(2, 7, 3, 7));
        JPanel1.add(NamSinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 290, 30));

        TenLop.setFont(new java.awt.Font("Futura Bk", 0, 16));
        TenLop.setText("Tên lớp");
        TenLop.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TenLop.setEnabled(false);
        TenLop.setMargin(new java.awt.Insets(2, 7, 3, 7));
        JPanel1.add(TenLop, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 290, 30));

        MSSV.setFont(new java.awt.Font("Futura Bk", 0, 16));
        MSSV.setText("MSSV");
        MSSV.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        MSSV.setEnabled(false);
        MSSV.setMargin(new java.awt.Insets(2, 7, 3, 7));
        JPanel1.add(MSSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 230, 30));

        Hoten.setFont(new java.awt.Font("Futura Bk", 0, 16));
        Hoten.setText("Họ tên");
        Hoten.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Hoten.setEnabled(false);
        Hoten.setMargin(new java.awt.Insets(2, 7, 3, 7));
        JPanel1.add(Hoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 230, 30));

        HocKy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        HocKy.setToolTipText("Học kỳ");
        HocKy.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                HocKyItemStateChanged(evt);
            }
        });
        JPanel1.add(HocKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 70, 30));

        NamHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017-2018", "2018-2019", "2019-2020", "2020-2021", "2021-2022", "2022-2023", "2023-2024" }));
        NamHoc.setSelectedIndex(6);
        NamHoc.setToolTipText("Năm Học");
        NamHoc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NamHocItemStateChanged(evt);
            }
        });
        JPanel1.add(NamHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 130, 30));

        MonHocCB.setSelectedItem("-Mã lớp-");
        MonHocCB.setToolTipText("");
        MonHocCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MonHocCBItemStateChanged(evt);
            }
        });
        JPanel1.add(MonHocCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 270, 30));

        jLabel9.setFont(new java.awt.Font("Futura Bk", 0, 18)); // NOI18N
        jLabel9.setText("Xếp loại môn học");
        JPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 160, 30));

        jLabel8.setFont(new java.awt.Font("Futura Bk", 0, 18)); // NOI18N
        jLabel8.setText("Học kỳ");
        JPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 60, 30));

        jLabel7.setFont(new java.awt.Font("Futura Bk", 0, 18)); // NOI18N
        jLabel7.setText("Năm học");
        JPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 80, 30));

        jLabel6.setFont(new java.awt.Font("Futura Bk", 0, 18)); // NOI18N
        jLabel6.setText("Môn");
        JPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 60, 30));

        jLabel2.setFont(new java.awt.Font("Futura Bk", 0, 18)); // NOI18N
        jLabel2.setText("Họ tên");
        JPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 60, 30));

        jLabel3.setFont(new java.awt.Font("Futura Bk", 0, 18)); // NOI18N
        jLabel3.setText("Tên lớp");
        JPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 60, 30));

        jLabel4.setFont(new java.awt.Font("Futura Bk", 0, 18)); // NOI18N
        jLabel4.setText("MSSV");
        JPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 60, 30));

        jLabel5.setFont(new java.awt.Font("Futura Bk", 0, 18)); // NOI18N
        jLabel5.setText("Năm sinh");
        JPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 90, 30));

        jLabel10.setFont(new java.awt.Font("Futura Bk", 0, 18)); // NOI18N
        jLabel10.setText("Điểm lần 1");
        JPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 100, 30));

        jLabel11.setFont(new java.awt.Font("Futura Bk", 0, 18)); // NOI18N
        jLabel11.setText("Điểm lần 2");
        JPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 100, 30));

        jLabel12.setFont(new java.awt.Font("Futura Bk", 0, 18)); // NOI18N
        jLabel12.setText("Trung bình môn học");
        JPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 170, 30));

        jLabel13.setFont(new java.awt.Font("Futura Bk", 2, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Chú ý: Sử dụng dấu chấm (.) cho điểm dạng thập phân.");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 480, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        if(con == null){
            JOptionPane.showMessageDialog(this, "Vui lòng kết nối trước!", "Chưa kết nối", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(exist==-1){
            JOptionPane.showMessageDialog(this, "Chưa chọn môn học", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String monhoc = String.valueOf(MonHocCB.getSelectedItem());
        int hocky = Integer.valueOf(String.valueOf(HocKy.getSelectedItem()));
        String namhoc = String.valueOf(NamHoc.getSelectedItem());
        float diem1;
        float diem2;
        try {
            diem1 = Float.valueOf(DiemL1.getText());
            diem2 = Float.valueOf(DiemL2.getText());
            if((diem1<0) || (diem1>10) || (diem2<0) || (diem2>10)) throw new Exception();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Điểm không hợp lệ", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (exist==0) {
            try {
                Statement s = con.createStatement();
                int r = s.executeUpdate("insert into Diem (DiemLan1, DiemLan2, MaMH, MSSV, HocKy, NamHoc) "
                        + "values ("+diem1+","+diem2+" ,(select MaMH from MonHoc where TenMH = N'"+monhoc+"'), "
                                + "N'"+Mssv+"', "+hocky+", N'"+namhoc+"');");

                JOptionPane.showMessageDialog(this, "Đã thêm " + r + " bảng điểm.", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                s.close();
                ReloadBtn.doClick();
                return;
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this,
                        "Không thêm được điểm sinh viên này, vui lòng kiểm tra lại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        }
        
        if (exist==1){
            int c = JOptionPane.showConfirmDialog(this, "Xác nhận thay đổi điểm?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if(c == JOptionPane.YES_OPTION){}
                else return;
            try {
                Statement s = con.createStatement();
                int r = s.executeUpdate("UPDATE Diem SET DiemLan1 = "+diem1+", DiemLan2 = "+diem2+
                            "WHERE MaMH = (select MaMH from MonHoc where TenMH = N'"+monhoc+"')" +
                            " AND MSSV = N'"+Mssv+"'" +
                            " AND HocKy = '"+hocky+"'" +
                            " AND NamHoc = N'"+namhoc+"';");
                
                JOptionPane.showMessageDialog(this, "Cập nhật thành công " + r + " bảng điểm.", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                s.close();
                ReloadBtn.doClick();
                return;
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this,
                        "Không sửa được, vui lòng kiểm tra lại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_SaveBtnActionPerformed

    public void reloadMonHoc(){
        try {
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("SELECT TenMH from MonHoc;");
            DefaultComboBoxModel<String> CBmodel = (DefaultComboBoxModel<String>) MonHocCB.getModel();
            
            while(rs.next()){
                CBmodel.addElement(rs.getString(1));
            }
            CBmodel.setSelectedItem("-Môn học-");
            s.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    private void ReloadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReloadBtnActionPerformed
        if(con == null){
            JOptionPane.showMessageDialog(this, "Vui lòng kết nối trước!", "Chưa kết nối", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {         
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("select MSSV, HoTen, NamSinh, TenLop from SinhVien inner join Lop on SinhVien.MaLop = Lop.MaLop where MSSV = N'"+Mssv+"';");
            
            rs.next();
            Object[] obj = {rs.getString("MSSV"), rs.getString("HoTen"), rs.getInt(3), rs.getString(4)};
            MSSV.setText(String.valueOf(obj[0]));
            Hoten.setText(String.valueOf(obj[1]));
            NamSinh.setText(String.valueOf(obj[2]));
            TenLop.setText(String.valueOf(obj[3]));
//            NamHoc.setSelectedIndex(6);
            loadDiem();
            s.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_ReloadBtnActionPerformed

    
    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        try {
            this.setVisible(false);
            QLTTSV.getInstance().reloadTTSV();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_CloseBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        int c = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa điểm này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if(c == JOptionPane.YES_OPTION){}
        else return;
        try {
            Statement s = con.createStatement();
            String monhoc = String.valueOf(MonHocCB.getSelectedItem());
            int hocky = Integer.valueOf(String.valueOf(HocKy.getSelectedItem()));
            String namhoc = String.valueOf(NamHoc.getSelectedItem());
            String exe = "delete Diem where MaMH = (select MaMH from MonHoc where TenMH = N'"+monhoc+"')" +
                " AND MSSV = N'"+Mssv+"'" +
                " AND HocKy = '"+hocky+"'" +
                " AND NamHoc = N'"+namhoc+"';";
            int x = s.executeUpdate(exe);
            if (x == 1) {
                JOptionPane.showMessageDialog(this, "Xóa thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                System.out.println("Da xoa diem mon hoc: " + monhoc);
                ReloadBtn.doClick();
            } else
                JOptionPane.showMessageDialog(this, "Chưa có điểm, không thể xóa", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Chưa có điểm, không thể xóa", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void DiemL1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiemL1MouseClicked
        try {
            float diem1 = Float.valueOf(DiemL1.getText());
            if((diem1<0) || (diem1>10)) throw new Exception();
        } catch (Exception e) {
            DiemL1.setText("");
            return;
        }
    }//GEN-LAST:event_DiemL1MouseClicked

    private void DiemL2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiemL2MouseClicked
        try {
            float diem2 = Float.valueOf(DiemL2.getText());
            if((diem2<0) || (diem2>10)) throw new Exception();
        } catch (Exception e) {
            DiemL2.setText("");
            return;
        }
    }//GEN-LAST:event_DiemL2MouseClicked

    private void XepLoaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XepLoaiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_XepLoaiMouseClicked

    private void DiemTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiemTBMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DiemTBMouseClicked

    private void MonHocCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MonHocCBItemStateChanged
        DiemL1.setText("Điểm lần 1");
        DiemL2.setText("Điểm lần 2");
        DiemTB.setText("Điểm TB");
        XepLoai.setText("Xếp loại");
        loadDiem();
    }//GEN-LAST:event_MonHocCBItemStateChanged

    private void NamHocItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NamHocItemStateChanged
        DiemL1.setText("Điểm lần 1");
        DiemL2.setText("Điểm lần 2");
        DiemTB.setText("Điểm TB");
        XepLoai.setText("Xếp loại");
        loadDiem();
    }//GEN-LAST:event_NamHocItemStateChanged

    private void HocKyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_HocKyItemStateChanged
        DiemL1.setText("Điểm lần 1");
        DiemL2.setText("Điểm lần 2");
        DiemTB.setText("Điểm TB");
        XepLoai.setText("Xếp loại");
        loadDiem();
    }//GEN-LAST:event_HocKyItemStateChanged

    public void loadDiem(){
        try {
            Statement s = con.createStatement();
            String monhoc = String.valueOf(MonHocCB.getSelectedItem());
            int hocky = Integer.valueOf(String.valueOf(HocKy.getSelectedItem()));
            String namhoc = String.valueOf(NamHoc.getSelectedItem());

            s.execute("UPDATE Diem\n" +
                        "SET XepLoai = \n" +
                        "    CASE\n" +
                        "        WHEN DiemTB BETWEEN 0 AND 3.99 THEN N'Rớt'\n" +
                        "        WHEN DiemTB BETWEEN 4.0 AND 5.49 THEN N'Yếu'\n" +
                        "        WHEN DiemTB BETWEEN 5.5 AND 6.99 THEN N'Trung Bình'\n" +
                        "        WHEN DiemTB BETWEEN 7.0 AND 8.49 THEN N'Khá'\n" +
                        "        WHEN DiemTB BETWEEN 8.5 AND 10.0 THEN N'Giỏi'\n" +
                        "		ELSE N'Không Thể Xếp Hạng!'\n" +
                        "    END;");
            ResultSet rs = s.executeQuery("Select DiemLan1, DiemLan2, DiemTB, XepLoai from Diem "
                    + "WHERE MSSV=N'"+Mssv+"' AND MaMH= (select MaMH from MonHoc where TenMH = N'"+monhoc+"')"
                    + "AND NamHoc = N'"+namhoc+"' AND HocKy = '"+hocky+"'");
            if(rs.next()){
                DiemL1.setText(String.valueOf(rs.getFloat(1)));
                DiemL2.setText(String.valueOf(rs.getFloat(2)));
                DiemTB.setText(String.valueOf(rs.getFloat(3)));
                XepLoai.setText(String.valueOf(rs.getString(4)));
                exist = 1;
            } else if(!monhoc.equals("-Môn học-")){
//                JOptionPane.showMessageDialog(null, "Môn học này chưa có điểm", "Thông báo", JOptionPane.OK_OPTION);
                exist = 0;
            }
            s.close();
        } catch (Exception e) {
            }
    }
    
    public void reloadTTSV(){
        this.ReloadBtn.doClick();
    }
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JTextField DiemL1;
    private javax.swing.JTextField DiemL2;
    private javax.swing.JTextField DiemTB;
    private javax.swing.JComboBox<String> HocKy;
    private javax.swing.JTextField Hoten;
    private javax.swing.JPanel JPanel1;
    private javax.swing.JTextField MSSV;
    private javax.swing.JComboBox<String> MonHocCB;
    private javax.swing.JComboBox<String> NamHoc;
    private javax.swing.JTextField NamSinh;
    private javax.swing.JButton ReloadBtn;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JTextField TenLop;
    private javax.swing.JTextField XepLoai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
